name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.13"]
        r-version: ["release"]

    steps:
    - uses: actions/checkout@v4
    - name: Set up R
      run: |
        sudo apt-get install -y r-base r-base-dev libcurl4-openssl-dev libssl-dev libxml2-dev libtirpc-dev
    - name: Install R dependencies
      run: |
        sudo R -e "install.packages('spOccupancy', repos='https://cloud.r-project.org')"
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Python dependencies
      run: |
        pip install -e .[dev]
        pip install rpy2  # for comparing to R packages
    - name: Test with unittest
      run: |
        python -m unittest -vvv
